name: TogglesDemo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build TogglesDemo
    runs-on: macos-15
    
    steps:
    - name: Show macOS version
      run: sw_vers

    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Select Xcode
      uses: TogglesPlatform/Pipelines/actions/select-xcode@v1
      with:
        xcode-version: 16.4.0

    - name: Check xcodebuild version
      run: xcodebuild -version

    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks

    - name: Show buildable schemes
      working-directory: ./TogglesDemo
      run: xcodebuild -list

    - name: Show eligible build destinations for TogglesDemo
      working-directory: ./TogglesDemo
      run: xcodebuild -showdestinations -scheme TogglesDemo
      
    - name: Build for destination TogglesDemo
      working-directory: ./TogglesDemo
      run: xcodebuild build -scheme TogglesDemo -destination "platform=iOS Simulator,OS=18.4,name=iPhone 16 Pro"
