name: TogglesDemo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  XCODE_VERSION: 15.2.0

jobs:
  test:
    name: Build
    runs-on: macos-14.2.1
    steps:
    - name: Show macOS version
      run: sw_vers
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Select Xcode
      uses: ./.github/actions/select-xcode
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      working-directory: ./TogglesDemo
      run: xcodebuild -list
    - name: Show eligible build destinations for TogglesDemo
      working-directory: ./TogglesDemo
      run: xcodebuild -showdestinations -scheme TogglesDemo
    - name: Build for destination TogglesDemo
      working-directory: ./TogglesDemo
      run: xcodebuild build -scheme TogglesDemo -destination "platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro"
