name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  publish-release:
    name: Publish release ${{ github.ref_name }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Create release
      id: create-release
      uses: TogglesPlatform/Pipelines/actions/create-release@v1
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        tag-name: ${{ github.ref_name }}
        