name: ToggleCipher

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  XCODE_VERSION: 15.2.0

jobs:
  test:
    name: Run tests
    runs-on: macos-14
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Select Xcode
      uses: ./.github/actions/select-xcode
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
    - name: Run tests
      working-directory: ./ToggleCipher
      run: swift test
